### ISSUE TITLE
SQL composition / parser error in Bigquery tap

### ISSUE THREAD

**Issue by mudam** [targetta/ankaflow#2]
When Autoranking is enabled the sqlglot parser sometimes fails.

Seems somehow related to ``` ` ``` delimiter.

Create tap:
```
- name: Test
  kind: source
  connection:
    kind: BigQuery
    locator: test_table
    version: version
    key:
      - id
  query: select * from BigQuery
  show: 1
```

Run and get error before the request gets disptached. Table name not rewritten.
```
ParseError in Test: Expecting ). Line 1, Col: 45.
  SELECT *, ROW_NUMBER() OVER (PARTITION BY `id` ORDER BY `version` DESC) AS `__rank__` FROM `BigQuery`
```

With ranking removed:
```
- name: Test
  kind: source
  connection:
    kind: BigQuery
    locator: test_table
    # version: version
    # key:
    #   - id
  query: select * from BigQuery
  show: 1
```

```
NotFound in Test: 404 Not found: Table zzz:www.test_table was not found in location US
```
We clearly see the query was disptached.
